### ISSUE TITLE
Unable to test the model by the given command

### ISSUE THREAD

**Issue by 02akshay** [FriedRonaldo/SinGAN#1]
When i'm running this command to train the model

python main.py --gpu 0 --img_to_use 0 --img_size_max 1025 --gantype zerogp --validation --load_model $(dir)

so I'm facing this issue

![Screenshot from 2019-11-05 13-50-27](https://user-images.githubusercontent.com/24732757/68190622-bf0d1a00-ffd3-11e9-9215-35d6e7c6bb25.png)

**Comment by FriedRonaldo** [comment]
$(dir) is the directory of the file ".ckpt". $blah means a variable.

For example, $(dir) can be "SinGAN_2019-07-19_15-25-14".

python main.py --gpu 0 --img_to_use 0 --img_size_max 1025 --gantype zerogp --validation --load_model "SinGAN_2019-07-19_15-25-14"
