### ISSUE TITLE
Error in usage

### ISSUE THREAD

**Issue by testerpce** [FriedRonaldo/SinGAN#3]
python main.py --gpu 0 --img_to_use 0 --img_size_max 1025 --gantype wgangp --model_name first_try
main.py:65: UserWarning: You have chosen a specific GPU. This will completely disable data parallelism.
  warnings.warn('You have chosen a specific GPU. This will completely '
Total Number of GPUs:                   1                                       
Total Number of Workers:                8                                       
Batch Size:                             1                                       
Max image Size:                         1025                                    
Min image Size:                         25                                      
Log DIR:                                ./logs/first_try_2020-02-10_20-08-29    
Result DIR:                             ./results/first_try_2020-02-10_20-08-29 
GAN TYPE:                               wgangp                                  
Use GPU: 0 for training
[25, 33, 44, 59, 79, 105, 140, 187, 249, 332, 443, 591, 789, 1052]
USE PHOTO DATASET
Traceback (most recent call last):
  File "main.py", line 339, in <module>
    main()
  File "main.py", line 109, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 224, in main_worker
    train_dataset, _ = get_dataset(args.dataset, args)
  File "/home/testerpce/Documents/ML_Experiments/CLAB/SinGAN/code/datasets/datasetgetter.py", line 87, in get_dataset
    train_dataset = PhotoData(args.data_dir, True, transform=transforms_train, img_to_use=args.img_to_use)
  File "/home/testerpce/Documents/ML_Experiments/CLAB/SinGAN/code/datasets/photoimage.py", line 28, in __init__
    self.image_dir = sorted(glob(os.path.join(self.image_dir, '*.jpg')))[img_to_use]
IndexError: list index out of range

I am getting an index out of range error. Is the code working in your case?

**Comment by FriedRonaldo** [comment]
Please set "img_to_use" to the value under the maximum number of the data that you have.
Or check the specified directory of the dataset - you did not specify the directory of the dataset in the command line.
